[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build]
  command = "npm run prebuild && npm run build-beta"
  functions = "functions"
  publish = "public"
