backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images/cms"
public_folder: "../../images/cms"
site_url: https://eaveswall.com
display_url: https://eaveswall.com
collections:
  - name: "article"
    label: "Article"
    folder: "src/posts/{{slug}}"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Author's Twitter",
          name: "author-twitter",
          widget: "hidden",
          default: "@eaveswall",
        }
      - {
          label: "Created Date",
          name: "date",
          widget: "date",
          format: "YYYY-MM-DD",
          default: "",
        }
      - {
          label: "Last modified",
          name: "last-modified",
          widget: "date",
          format: "YYYY-MM-DD",
          default: "",
        }
      - { label: "Description", name: "desc", widget: "text" }
      - {
          label: "Tags",
          name: "tags",
          collapsed: false,
          widget: "list",
          default: ["featured"],
        }
      - {
          label: "Thumbnail",
          name: "featuredImage",
          widget: "image",
          media_library: { config: { multiple: false } },
        }
      - { label: "Publish", name: "publish", widget: "hidden", default: true }
      - { label: "Slug", name: "slug", widget: "string", default: "/title-in-kebab-case" }
      - {
          label: "Post Content",
          name: "body",
          widget: "markdown",
          buttons:
            [
              "bold",
              "italic",
              "heading-two",
              "heading-three",
              "heading-four",
              "link",
              "bulleted-list",
              "numbered-list",
              "quote",
            ],
        }

  - name: "persona"
    label: "Persona Feature"
    folder: "src/wiki/persona"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Description", name: "desc", widget: "text" }
      - {
          label: "Tags",
          name: "tags",
          collapsed: false,
          widget: "list",
          default: ["featured", "persona"],
        }
      - {
          label: "Thumbnail",
          name: "featuredImage",
          widget: "image",
          media_library: { config: { multiple: false } },
        }
      - { label: "Publish", name: "publish", widget: "hidden", default: false }
      - {
          label: "Post Content",
          name: "body",
          widget: "markdown",
          buttons:
            [
              "bold",
              "italic",
              "heading-two",
              "heading-three",
              "heading-four",
              "bulleted-list",
              "numbered-list",
              "quote",
            ],
        }
